import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary:       'rgb(var(--color-primary) / <alpha-value>)',
        'primary-fg':  'rgb(var(--color-primary-fg) / <alpha-value>)',
        accent:        'rgb(var(--color-accent) / <alpha-value>)',
        'accent-fg':   'rgb(var(--color-accent-fg) / <alpha-value>)',
        surface:       'rgb(var(--color-surface) / <alpha-value>)',
        'surface-alt': 'rgb(var(--color-surface-alt) / <alpha-value>)',
        border:        'rgb(var(--color-border) / <alpha-value>)',
        muted:         'rgb(var(--color-text-muted) / <alpha-value>)',
        success:       'rgb(var(--color-success) / <alpha-value>)',
        warning:       'rgb(var(--color-warning) / <alpha-value>)',
        danger:        'rgb(var(--color-danger) / <alpha-value>)',
        ocean:         'rgb(var(--color-ocean) / <alpha-value>)',
        'ocean-deep':  'rgb(var(--color-ocean-deep) / <alpha-value>)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'Georgia', 'serif'],
        body:    ['var(--font-body)', 'system-ui', 'sans-serif'],
        sans:    ['var(--font-body)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'fluid-xs':   'var(--text-xs)',
        'fluid-sm':   'var(--text-sm)',
        'fluid-base': 'var(--text-base)',
        'fluid-lg':   'var(--text-lg)',
        'fluid-xl':   'var(--text-xl)',
        'fluid-2xl':  'var(--text-2xl)',
        'fluid-3xl':  'var(--text-3xl)',
        'fluid-4xl':  'var(--text-4xl)',
        'fluid-5xl':  'var(--text-5xl)',
        'fluid-6xl':  'var(--text-6xl)',
        'fluid-7xl':  'var(--text-7xl)',
      },
      spacing: {
        'fluid-3xs': 'var(--space-3xs)',
        'fluid-2xs': 'var(--space-2xs)',
        'fluid-xs':  'var(--space-xs)',
        'fluid-sm':  'var(--space-sm)',
        'fluid-md':  'var(--space-md)',
        'fluid-lg':  'var(--space-lg)',
        'fluid-xl':  'var(--space-xl)',
        'fluid-2xl': 'var(--space-2xl)',
      },
      boxShadow: {
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        xl:    'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        glow:  'var(--shadow-glow)',
      },
      borderRadius: {
        xs:    'var(--radius-xs)',
        sm:    'var(--radius-sm)',
        md:    'var(--radius-md)',
        lg:    'var(--radius-lg)',
        xl:    'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
      },
      transitionTimingFunction: {
        out:    'var(--ease-out)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
      animation: {
        'fade-in':    'fadeIn 250ms var(--ease-out) both',
        'fade-up':    'fadeUp 600ms var(--ease-out) both',
        'fade-down':  'fadeDown 250ms var(--ease-out) both',
        'scale-in':   'scaleIn 250ms var(--ease-spring) both',
        'slide-in':   'slideIn 300ms var(--ease-out) both',
        shimmer:      'shimmer 2s linear infinite',
        float:        'float 6s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 2.5s ease-in-out infinite',
        'gradient-x': 'gradientX 8s ease infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeUp:    { from: { opacity: '0', transform: 'translateY(28px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeDown:  { from: { opacity: '0', transform: 'translateY(-12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:   { from: { opacity: '0', transform: 'scale(0.94)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideIn:   { from: { opacity: '0', transform: 'translateX(-20px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        shimmer:   { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        float:     { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        pulseSoft: { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.85', transform: 'scale(1.04)' } },
        gradientX: { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
      },
    },
  },
  plugins: [],
}

export default config
